version: 0.2

phases:
  pre_build:
    commands:
      - echo "Starting the build"
      - aws ecr get-login-password --region us-east-2 | docker login --username AWS --password-stdin 533267339721.dkr.ecr.us-east-2.amazonaws.com
  build:
    commands:
      - echo "Build started on `date`"
      - echo "Building the Docker image..."
      - docker build -t mmd .
      - docker tag mmd:latest 533267339721.dkr.ecr.us-east-2.amazonaws.com/mmd:latest
  post_build:
    commands:
      - echo "Build completed on `date`"
      - echo "Pushing the Docker image..."
      - docker push 533267339721.dkr.ecr.us-east-2.amazonaws.com/mmd:latest
      - echo "Pushed the Docker image"
