name: CI Pipeline

on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types:
      - completed

jobs:
  build:
    runs-on: self-hosted

    steps:
    - name: Pull Docker Image
      run: docker pull cristhianzl/cicd-pipeline:latest
    name: Delete Old Docker Container
      run: sudo docker rm -f cicd-pipeline || true
    - name: Run Docker Container
      run: docker run -d -p 4200:4200 --name cicd-pipeline cristhianzl/cicd-pipeline:latest
